### ISSUE TITLE
Improve the world

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#10]
* reading minecraft save ?
* generating something better ?

**Comment by rom1504** [comment]
completely depends on #19

**Comment by demipixel** [comment]
Definitely want to read/write as a normal minecraft world so anybody from a server or survival world can simply drag it in.

Later we can think about making a compressed version so they're faster to send or what not (or if it's possible to make worlds larger than vanilla? idk, that probably is limited by the client).

**Comment by rom1504** [comment]
ok so prismarine-world is there, we can use its api, it shouldn't change too much, only its implementation will change but we don't care about that.

**Comment by rom1504** [comment]
now handled in #47 and prismarine-world issues.
