### ISSUE TITLE
Infinite loop whenever a block is broken

### ISSUE THREAD

**Issue by 109C** [mhsjlw/flying-squid#103]
Steps to reproduce bug:

* start server.
* break block.
* 100% cpu usage and eventually the clients time out.

Happens in both survival and creative.
This *might* be related to #99, however I'm not sure so that's why I made a separate Issue.

**Comment by rom1504** [comment]
Is that in gamemode 0 ?

**Comment by 109C** [comment]
No, it's in creative *and* survival.
