### ISSUE TITLE
Crash when trying to use non-block item on a block

### ISSUE THREAD

**Issue by 109C** [mhsjlw/flying-squid#104]
Tested with these materials, and the crash always happens.
* Water bucket
* Creeper / Zombie / etc spawn egg
* Raw beef / steak / etc

```
/Users/C109/Desktop/squid_new/dist/lib/plugins/placeBlock.js:49
        throw err;
              ^
TypeError: Cannot read property 'material' of undefined
    at /Users/C109/Desktop/squid_new/dist/lib/plugins/placeBlock.js:30:69
    at run (/Users/C109/Desktop/squid_new/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/C109/Desktop/squid_new/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/C109/Desktop/squid_new/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
```

**Comment by rom1504** [comment]
Ah this is http://wiki.vg/Protocol#Player_Block_Placement "This packet has a special case where X, Y, Z, and Face are all -1."
which we do ignore there https://github.com/mhsjlw/flying-squid/blob/master/src/lib/plugins/placeBlock.js#L17
So it shouldn't crash. got to check the value of direction to see why that happens.

It's also kind of related to https://github.com/mhsjlw/flying-squid/issues/9

**Comment by 109C** [comment]
It seems the listener in plackBlock never fires, I added a couple of console.logs and they didn't fire when I put down a normal block, nor when I tried with the item.

**Comment by rom1504** [comment]
@109C did you run `gulp` after adding your console.log ?

**Comment by 109C** [comment]
@rom1504 Thanks, I forgot to ```npm install```.

**Comment by 109C** [comment]
Ok, so I got the logging working and it seems direction is -1 if you're not looking a block (aka it is outlined), but it sends valid block faces when the item is used while looking at a block.

This means ```block_place``` is ambiguous, and there are actually *four* cases:
* block, looking at block. (should be place)
* block, not looking at block. (should not be place)
* item use, looking at block. (should be use)
* item use, not looking at block. (should be use)

**Comment by rom1504** [comment]
When you don't look at a block, block_place is not sent it seems.

I added a check to do nothing when you are not holding a block.

So, the crash is fixed. But using items is still not implemented, we can track this feature there https://github.com/mhsjlw/flying-squid/issues/106
