### ISSUE TITLE
Fix killing Dragons

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#109]
It's possible to kill zombie, but not dragons apparently.
(test it by doing /summon EnderDragon)

**Comment by rom1504** [comment]
It seems dragons have at least 8 entity ids (as shown by console.log(entityId) in attackEntity).
We need to figure out what this is about to fix that issue (see http://minecraft.gamepedia.com/Dragon)

**Comment by 109C** [comment]
It's probably the different parts of the dragons that have different UEIDs.

**Comment by rom1504** [comment]
Maybe, but how many parts does it have ? (8 is only a minimum, there might been some parts I didn't hit)

**Comment by rom1504** [comment]
> 20:48 <+Thinkofname> 7 parts + dragon itself
>20:48 <+Thinkofname>         this.children = new EntityComplexPart[] { this.bn = new
> EntityComplexPart(this, "head", 6.0F, 
>                     6.0F), this.bo = new EntityComplexPart(this, "body", 8.0F, 8.0F), this.bp = new 
> EntityComplexPart(this, 
>                     "tail", 4.0F, 4.0F), this.bq = new EntityComplexPart(this, "tail", 4.0F, 4.0F), this.br = new 
>                     EntityComplexPart(this, "tail", 4.0F, 4.0F), this.bs = new EntityComplexPart(this, "wing", > 4.0F, 4.0F), 
>                     this.bt = new EntityComplexPart(th
> 20:48 <+Thinkofname> is, "wing", 4.0F, 4.0F)};

And this is apparently the only multi parts entity.
