### ISSUE TITLE
Players sometimes duplicate if the client leaves when loggin in

### ISSUE THREAD

**Issue by 109C** [mhsjlw/flying-squid#113]
Console output:
```
November 22nd 2015, 13:06:24 [INFO]: ff1223 connected
November 22nd 2015, 13:06:24 [INFO]: position written, player spawning...
November 22nd 2015, 13:06:26 [INFO]: undefined disconnected
```
When the player logs back in:
![example of player duplication](http://i.imgur.com/AOZg2gs.png)

**Comment by rom1504** [comment]
I'm not sure why this happens. Got to check if what's in logout.js is properly used in this case or not (add some console.log for testing)

**Comment by demipixel** [comment]
Disconnect before logging in, anything from cancel to being banned (i.e. already banned)

**Comment by 109C** [comment]
@demipixel Yes.

**Comment by rom1504** [comment]
that's the test case yes, but that's not the cause

**Comment by rom1504** [comment]
I figured out why it happens : entity plugins are loaded before player plugins, which means logout.js is loaded some time after the player logins.
If the player logout too early, then the 'end' listener is never called.

**Comment by rom1504** [comment]
oh actually, it even happens before entity plugins loading, it happens before the nmp 'login' event is even emitted.
