### ISSUE TITLE
All drops, objects, entity related code is in plugins/entities.js

### ISSUE THREAD

**Issue by 109C** [mhsjlw/flying-squid#117]
It would be easier to read, and more simple to put them in their own non-plugin files, eg Player.js, DroppedItem.js, etc. Lots of the code is duplicated (object.yaw, mob.yaw), not to mention the object class is actually the dropped item class!

I'll be doing this myself, as dropped items effects inventories. (read: pickup / dropping items)

Unless anyone has any objections?

**Comment by rom1504** [comment]
yes sure, choose good file names though (and try to reuse the ones that exist if possible)
file names start with a lower case letter here ;)

**Comment by 109C** [comment]
Even if that file is a class file? Would ItemStack's class file be ` itemStack.js`?

**Comment by rom1504** [comment]
Yes, that's the convention in node.

**Comment by 109C** [comment]
Ok, I'll be doing this when @demipixel finishes with the entity behaviors.

**Comment by demipixel** [comment]
@109C should be soon. Also, if you're interested, maybe make dropped items stack together? (In vanilla, if you drop 64 items, they all merge into one ground of 64)

**Comment by 109C** [comment]
@demipixel I plan to implement that, after we figure out how to entity. (We don't even have a dropped item class yet.)

**Comment by rom1504** [comment]
Ah "Player.js, DroppedItem.js, etc. " , I didn't really this correctly. No I'd better if we can avoid that as much as possible for most entities.
It might be needed for some specific entities, and even then we can probably do something smarter like defining AI behavior function for each kind of entity, etc...

So: no I'm not for making one class by type of entity.

I cut the entities.js file in what it was doing : spawn.js, physics.js, updatePosition.js, ...
