### ISSUE TITLE
Chat colors and "links"

### ISSUE THREAD

**Issue by demipixel** [mhsjlw/flying-squid#118]
Okay, so you can do a lot of things in chat. For basic examples it would be nice to use strings:

`"Hello§1Red"` or better yet `"Hello" + CHAT.RED + "Red"`

Same with others colors, bold, italics, underline, cross-out, random, etc. This string would be converted to JSON for you.

Then there comes more complicated things... Like something happens when you click on text or what text appears when you hover over text. This would most likely be done with JSON manually or something.

**Comment by rom1504** [comment]
How do you do this in vanilla ?

**Comment by 109C** [comment]
@demipixel `&` is the informal standard to use colors, while you cannot type `§` into the chat.

@rom1504 It's sent in this format:
```
{
  text: "thanks for the good bones",
  color: "white",
  bold: true,
  extra: [
    {
      text: "mr skeletal"
    }
  ]
}
```

**Comment by rom1504** [comment]
I'm not asking how it is sent, I'm asking how to you send that kind of stuff from the chat in the game. (so it is displayed with the colors and all)

**Comment by demipixel** [comment]
@109C I don't want it usable in chat (plugins can allow that if they want)

@rom1504 /tellraw command (look at mc wiki)

**Comment by rom1504** [comment]
"I don't want it usable in chat" : where do you want to use it then ?

**Comment by demipixel** [comment]
In places like broadcast or broadcastJSON or something. For example, in my redditbuilds.js, it's very hard to read the text. It would be nice to color it to organize it a bit. (Plus we'll need it if we ever implement tellraw). Colors/Bold/Etc also work on signs, btw. (Users still can't do this but plugins do).

**Comment by rom1504** [comment]
hmm, is it really a good idea to use that kind of text format instead of json ? Can't we directly build the json or have helper functions to help us build that json ?

**Comment by 109C** [comment]
It's easier to read and build `hi&nthere` than `{text:"hi", extra:{text:"there", underline:true}}`, both for plugins and players. (Which are the same thing, actually)

**Comment by demipixel** [comment]
Yes that's what I meant. Allow something like broadcast("This is in white. &rThis is in red")

and

broadcast("This is in white. \&rThis has funny symbols before it");

As well as broadcastJSON for the format @109C mentioned. You need that for more complicated things like hovering text or clicking to do something.

**Comment by rom1504** [comment]
Done, see #167 for remaining fixes.
