### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#120]
We sure need automated testing. Testing all the features manually after each change is becoming less and less reasonable.
Ideas:
* run all the commands with different parameters, check that the server doesn't crash
* run a nmp (or mineflayer) client and make it does various stuff, check that the server doesn't crash

**Comment by demipixel** [comment]
Have the mineflayer run the commands, some of the commands require a user

**Comment by 109C** [comment]
@demipixel Also, having an independent client is better than one that's integrated, because it doesn't have the risk of changing the server's response.

**Comment by rom1504** [comment]
@109C sure, but running (and doing action on) the vanilla client automatically is much harder than running mineflayer. So we will probably start with mineflayer (or a simple nmp client)

**Comment by rom1504** [comment]
started in 44d721d2a55560a2017dc08a6c8473120f9355a8

**Comment by rom1504** [comment]
I think running exactly this test would be interesting https://github.com/andrewrk/mineflayer/blob/master/test/externalTests/digAndBuild.js

**Comment by rom1504** [comment]
I added some tests, I'll open more specific issues if needed
