### ISSUE TITLE
Fix "100% allocated" memory usage in vanilla client

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#127]
Even without moving.
I guess the problem is we are either (or both):
* [x] sending too many chunks
* [ ] sending whole columns
* [x] not unloading

It would be nice to check with mineflayer (or nmp), how many chunks the vanilla server send. (and which part of the chunks)

**Comment by rom1504** [comment]
render distance might be min(render_distance_server, render_distance_client) in vanilla

**Comment by rom1504** [comment]
Well I'm getting 100% allocated on a vanilla server too ?!

**Comment by 109C** [comment]
Did you restart your client? It still keeps them loaded even when you leave a server.

**Comment by rom1504** [comment]
Ah indeed restarting my client solved it on the vanilla server.

**Comment by rom1504** [comment]
and I don't get 100% allocated without moving, so indeed unloading chunks would be useful.

**Comment by rom1504** [comment]
now doing min(serverView,clientView) because the vanilla server does it (I checked)

there seems to be some kind of bug in the thing that computes which chunk should be unloaded but I can't quite figure out what http://download.rom1504.fr/stuff/mc-fall.png

if anybody can figure it out https://github.com/mhsjlw/flying-squid/blob/master/src/lib/plugins/world.js#L118 , I'm surely missing something obvious.

**Comment by rom1504** [comment]
fix that bug in 6d098deb23ee0a6c91be09f8527882aba1be3306

**Comment by rom1504** [comment]
sending whole column can be done later
