### ISSUE TITLE
Announce github url on join ?

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#137]
Just a `player.chat("Flying-squid server https://github.com/mhsjlw/flying-squid");` at https://github.com/mhsjlw/flying-squid/blob/master/src/lib/plugins/login.js#L169 
Useful for people that find the test server from other sources, but it's a bit annoying for people that already know about it.

**Comment by mhsjlw** [comment]
Maybe we could have people acknowledge the message so it doesn't show up again.

**Comment by rom1504** [comment]
let's not do that, it's not that useful
