### ISSUE TITLE
Have a look at stuff that use js as a plugin for minecraft

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#141]
For example 
* scriptcraft https://github.com/walterhiggins/ScriptCraft/blob/master/src/main/js/plugins/homes/homes.js

I don't know anything about it. Maybe they have interesting stuff we could use ?

Worth taking a look anyway.

**Comment by 109C** [comment]
Looking around the codebase, it seems to mostly be a java-js bridge to the bukkit API [using rihno](https://github.com/walterhiggins/ScriptCraft/blob/master/src/main/java/bukkit/org/scriptcraftjs/bukkit/ScriptCraftPlugin.java#L32). (Which is [bundled by default with the JDK?!?](http://docs.oracle.com/javase/7/docs/technotes/guides/scripting/programmer_guide/#jsengine))

Ecmascript API wise, it seems to me a little bit weird to have globals just there: `plugin()`, `command()`, etc. And anyways, our plugins currently are of a completely different structure.

**Comment by rom1504** [comment]
yeah, it doesn't seem very useful to us.

**Comment by rom1504** [comment]
related: http://wiki.sk89q.com/wiki/WorldEdit/Scripting and http://dev.bukkit.org/bukkit-plugins/easyscript/
