### ISSUE TITLE
Add an unhandled rejection listener

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#150]
https://nodejs.org/api/process.html#process_event_unhandledrejection

That should catch any error coming out of promises we didn't .catch

**Comment by demipixel** [comment]
#154

**Comment by rom1504** [comment]
@demipixel if you put "fix #154" in a commit message, it automatically close #154 when the commit is merged in master

**Comment by demipixel** [comment]
lol time to troll with my commit messages fix #1 fix #2 fix #3 fix #4 fix #5.........
