### ISSUE TITLE
Don't return errors, throw them

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#152]
https://github.com/mhsjlw/flying-squid/blob/master/src/lib/plugins/commands.js#L219

**Comment by demipixel** [comment]
The point of those was to distinguish they were an error. Since serv.selectorString is probably from a player, we don't want to have to constantly try/catch. Perhaps it's better if we return a string (with the error of course). Or...

Throw errors in serv.selector and return strings in serv.selectorString. Try/catch in serv.selectorString and convert err to string.

**Comment by rom1504** [comment]
"we don't want to have to constantly try/catch", throwing actually give us the choice to deal with the error right now by try/catching or let the error propagate. Return forces us to deal with the error right now.

But really throwing is the correct way to do errors in js, especially now that we have promises that are compatible with throw/catch (unlike callback that have their own error handling convention)

So yeah I think we should try/catch when using selectorString since it can fail.

**Comment by rom1504** [comment]
throwing also give the possibility of not try/catching in the command definition itself but directly in Command.use (and return the error message to the player)

**Comment by demipixel** [comment]
I want to point out in commands, you return in action() to return an error (in my other PR I've changed the color of returned text to red) so if it returns a string, you just return the value.

The main point is that it's gonna throw an error if you try to do something like val[0].health or val.forEach.

**Comment by rom1504** [comment]
"you return in action() to return an error", yes and it's probably not a good pattern, that didn't cause problem until now because we didn't need to precise what kind of error it was

**Comment by demipixel** [comment]
It's already in red, it's just in my unaccepted PR :P

**Comment by rom1504** [comment]
> 18:55 < demipixel> @rom1504 the reason I don't want to throw errors is because I don't want to mix them up with user errors
> 18:55 < demipixel> Like, invalid select for
> 18:55 < demipixel> format VS passing in an object or undefined instead of a string
> 18:56 < demipixel> Obviously they might not want to output EVERY error.toString() to the user
> 18:56 < demipixel> Just string/user errors
> 19:10 < rom1504> ah indeed good point. One way to distinguish user errors from the other kinds is to extend the Error class 
>                  (like http://dailyjs.com/2014/01/30/exception-error/)
> 19:11 < rom1504> so we can do if(err instanceof UserError) player.chat("say error in red");
> 19:11 < rom1504> else setTimeout..

**Comment by demipixel** [comment]
#154
