### ISSUE TITLE
check if /tp works as intended for relative position and tp an other player

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#157]
> 22:47 < rom1504> "ff1223: Bug: when teleporting a player to a relative co-ordinate, it's relative to the target player, not 
>                  the player that issued the command" @demipixel you did this, isn't it working as intended ?
> 22:47 < rom1504> idk what vanilla mc does in that case
> 22:48 < 109C> It teleports it relative to the sender

**Comment by demipixel** [comment]
It's relative to the target

**Comment by rom1504** [comment]
ok, so it works right.
