### ISSUE TITLE
check if the selector returned anything before using it 

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#159]
https://github.com/mhsjlw/flying-squid/blob/master/src/lib/plugins/tp.js#L17

**Comment by rom1504** [comment]
done in 9366c1b9a77a94ef61418e6e92596bbd623fc536

**Comment by demipixel** [comment]
Need to check both entities_from and entity_to, not just one.

**Comment by rom1504** [comment]
yes, I did that fix in 47c75671c44460a667ccdf536ec471503d8e6dd9
