### ISSUE TITLE
Portal Glitch

### ISSUE THREAD

**Issue by melerpe** [mhsjlw/flying-squid#171]
How to reproduce, make a portal. Break portalblock (Not obsidian), place 1 ore two obisidian in portal, relight portal. Remove two obsidian blocks. Remove fire. Light it.
It doesn't work then!
Tested it multiply times!

**Comment by rom1504** [comment]
The bug here is `Remove fire`.
What is that ? Is it possible to remove fire in vanilla ?
Do we handle that ? I bet we don't.

**Comment by rom1504** [comment]
ah what we don't support is making fire. So the server doesn't know about the fire which was placed. Not sure what's the consequence of that exactly.

**Comment by rom1504** [comment]
@melerpe fixed ;)
