### ISSUE TITLE
Implement banning and kicking

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/flying-squid#27]
Because, why not?

**Comment by mhsjlw** [comment]
@rom1504 and I are on the scene

**Comment by rom1504** [comment]
That's easy.
Implement a player.kick and player.ban (ban == you can't join, and kick == player._client.end(kickReason) )
Then create things that call these 2 methods, for example : 
* create a /kick and a /ban 
* /kick someone if he's being mean (for example if he's saying bad things about squids in the chat)

**Comment by rom1504** [comment]
(I don't like the enhancement label : every issue is an enhancement.)

**Comment by mhsjlw** [comment]
@rom1504 I'll assign myself and do it know. Should I save all of the banned players in a file?

**Comment by rom1504** [comment]
I don't think it's really necessary for now, but if you want to do it, do it ;)

**Comment by rom1504** [comment]
done by @demipixel , but now we need #41
