### ISSUE TITLE
The "how should plugins work" problem

### ISSUE THREAD

**Issue by demipixel** [mhsjlw/flying-squid#32]
https://gist.github.com/demipixel/6532869a9fb7454a5a19

Only read below once you have read the whole gist:

Using this method, we can actually HAVE core plugins. The core plugin will:

- Emit the X_cancel event and after the X event.
- Act as a default if no plugin intervenes

For example, blockPlace.js would do the above. Nobody should ever have to remove blockPlace.js because otherwise you're basically saying "I'm going to either handle it myself or screw over any plugin that attempts to use this event". In addition, you'll simply have to rewrite the default (if you need it).

This is why I suggest having core plugins which cannot be edited for this reason. They are important for all plugins to use. Also, how would you even manage that? If one plugin needed to use the blockPlace.js plugin and the other wanted to rewrite it, it's not like one could simply remove the blockPlace.js one. There is absolutely no reason to remove a core plugin, and hence I believe that they should be separate. This is great, because now it cleans out basic plugins from node_modules so you're left only with the plugins you need :)

The only possible case where this would not work is if a plugin needed to overwrite a default but didn't want to act as a cancel. Almost no plugin should EVER have to do that, but if for one reason or another they do, we might add a secretCancel() which allows you to stop the default without the cancelled variable being true (unless, of course, another plugin does cancel()). I can't think of any time this would happen, so I'm not too worried if it's something clunky like that.

Thanks for your time,

DemiPixel

**Comment by rom1504** [comment]
"There is absolutely no reason to remove a core plugin" : yes there is : someone doesn't want the normal placeBlock thing and instead wants weird stuff like in #31 (or like my idea of : place a block = get killed and replaced by a squid)

"Emit the X_cancel event and after the X event.
Act as a default if no plugin intervenes"
This just isn't a thing in node.js. It will really be dirty if you need to "wait", like wait how much time ? what if the plugin is slow ? you wait 10s ?

As @roblabla said you are talking about 2 different things : 
* reusability : I think if you want to reuse some functionnality of a plugin, you should just be able to do that (which is totally possible if the plugin expose its methods, which it should)
* being able to implement something new : this is totally doable and easy with the current architecture

I really really think that not doing something, not installing it, is better than trying to uninstall it, or even worse cancelling.

Cancelling : what does that mean ? when do you cancel ? what if the plugins listen on n interconnected events and do stuff ? how can you cancel that ? reading the code of the plugin and being careful to break everything the plugin is doing is not a correct way to do it.

So what I propose is that once a few plugins are implemented with the current architecture, if it still seems too complicated/wrong to you, you can try to implement your way in a PR and we'll see if it makes everything easier.

**Comment by demipixel** [comment]
> yes there is : someone doesn't want the normal placeBlock thing and instead wants weird stuff like in #31 (or like my idea of : place a block = get killed and replaced by a squid)

```js
function inject(serv, player) {
  player.on('place_block_cancel', function(block, cancel) {
      serv.spawnMob('squid', block.location);
      cancel();
  });
}
```
The point of this WAS that you could completely overwrite the default with no trouble at all and wouldn't have to worry about it happening (unless some plugin is an asshole).

As for a plugin waiting... if a plugin is going to take up 10 seconds to run, that's going to be a lot of time regardless. And in the long run, it might be okay if you take longer if you're canceling (won't run default code anyway).

**Canceling:** It cancels the DEFAULT action. If any plugin cancels, the default action will not run (assuming fuckOtherPlugins() isn't but my reaction to that is in the name).

I can't tell if you're talking about interconnected plugins here, but not, this does not support interconnected plugins. You can NEVER be sure about the order, so this will never happen unless we add a way to order them.

If you still don't understand or don't agree, we'll simply do your proposal at the bottom.

Cheers,

Demi

**Comment by rom1504** [comment]
I was talking about interconnected events, like inventory stuff are really interconnected, you can't just ignore half of it, you'd need to disable the whole inventory plugin if you want to do it differently.

"you could completely overwrite the default with no trouble at all and wouldn't have to worry about it happening" : yes you are able to do that with the current architecture, and I'm pretty sure it would actually be hard to implement the cancel thing

You can't cancel like that. What you could do is remove the listener with removeListener, but really a plugin can do more than act on one event.

I think it makes much more sense to disable the whole plugin and then to use the exposed methods of that plugin if you want the default thing in most cases.

**Comment by rom1504** [comment]
We might want to look at https://github.com/voxel/voxel-plugins

**Comment by rom1504** [comment]
Some thoughts about this:
I think a clean way to do all this might be to extend EventEmitter in a BehaviourEmitter class, and override the on method with something like on("behaviour","event",func) . This on would not directly add the listener. It would add that behaviour to a behaviourEmitter.behaviours array.
Then we would call a behaviourEmitter.enable("behaviour") function that would actually enable the listener, and it would store that listener in a behaviourEmitter.enabledBehaviours. That would make it possible to do behaviourEmitter.disable("behaviour") whenever needed.
It would be possible to group these behaviours in plugins, if that's useful (for example, all the behaviour for changing the world would be in a var worldBehaviour=["digging","placingBlock"]; so we can easily enable/disable changing the world).

This would allow to enable/disable plugins and features easily and dynamically.

We could probably integrate that "cancellable event" thing in this class too (see https://github.com/mhsjlw/flying-squid/pull/49/files#diff-768337bda2bb1cbce3e9d7001bb76454R3 )

**Comment by demipixel** [comment]
Well, if a plugin wanted to "disable" an event, couldn't they simply always cancel it? I wonder if we could apply the same idea to disabling listeners rather than emitters, though, so we could disable plugins.

**Comment by rom1504** [comment]
what do you mean by "listener" ?

and I think it's much cleaner to actually not enable behaviours, than trying to cancel stuff afterwards. The cancelling thing is only potentially useful for dynamic stuff.

**Comment by demipixel** [comment]
Plugins are dynamic. Why would you want to cancel all world events? in that case, we can't even respond to the client saying "You can't place a block there" (i.e. replace whatever block they placed with air).

By listener I mean:

```js
// Plugin A
server.on('something', () => {});
```

Being able to emit 'something' from server to other plugins but not Plugin A if it's disabled. #83

**Comment by rom1504** [comment]
Most plugins won't need to disable some stuff only in some case, most plugins won't even need to cancel anything.
We might want to disable all world modification behaviors (!= events) to make a map viewer mode for example.
yeah well that doesn't make much sense.

We shouldn't cancel events at all. It doesn't make any sense, an event is going to happen anyway. What makes sense to cancel is a behavior/ a reaction.

**Comment by demipixel** [comment]
My definition of cancelling event consists of cancelling the default behavior to it (e.g. User places block, default = send to everybody). The event doesn't get cancelled and, with my special formula, sort of gets emitted twice. @roblabla considered this to be a behavior that any plugin could make and any other plugin could cancel as well, but I never really went for it since I figured plugins should be built with other plugins in mind, but not *for* other plugins.

**Comment by demipixel** [comment]
Using this method to solve #31 

https://gist.github.com/demipixel/301537f68b0aeec5eb83

**Comment by rom1504** [comment]
Summarizing what we talked about:
* each plugin (both core and "external") will follow a module.exports={player:...,server:...,entity:...} structure : that means we don't have 2 sound.js as currently for example but only one file in plugins/
* entity plugins : they will handle stuff that are general to all entities (physics, interaction with other entities, ...) and player plugins will handle stuff specific to players
* instead of player.entity we might just consider player a kind of entity (with some special function defined in player plugins like ._client)
* cancelling will be available

**Comment by roblabla** [comment]
So `player` is just a convenience around 
`entity: function(e) if (e is 'player') // do stuff`?

**Comment by rom1504** [comment]
@roblabla yeah basically. It's useful since players still have some amount of stuff that other entities don't.
(If some other entity were to need lot of code in the future I guess we could create a specific plugin type for it (plugins types are mostly for convenience since if we wanted we could do everything in server plugins))

**Comment by rom1504** [comment]
One more point: the plugins to load (and their settings) should be listed either in config/settings.json either in config/plugins.json (might be simpler to put it in settings.json to have just one file).
Doing that for both "internal" and "external" plugins would make it more coherent and easier to disable any part of flying-squid.

**Comment by demipixel** [comment]
My argument for @rom1504 's edit (to anybody reading this) was that so much of the vanilla internal plugins rely on each other to the point where disabling one plugin would disable a large chain and there's no easy way to prevent this. For an external plugin relying on an external plugin, however, I can see this being useful.

**Comment by mhsjlw** [comment]
I still agree with @rom1504's suggestion for using npm with plugins and I think we should still do that. As far as cancelling events go, I think we shouldn't be touching that incase another plugin external or internal needs that event for a feature then another plugin breaks that plugin.

**Comment by demipixel** [comment]
@mhsjlw Only defaults are cancelled, not events. The only reason you wouldn't get an event is if the internal plugin was disabled.

**Comment by demipixel** [comment]
Okay, we've done that ^^^

So I'm gonna requireindex both ./node_modules and ./plugins? What about also checking if ../node_modules exists and checking there as well? (If there's a wrapper for the server or something)?

The rest is just crap loads of behaviors. Change every event to a behavior and add even more behaviors and then pay a peasant $0.001 per behavior they document.

**Comment by rom1504** [comment]
> So I'm gonna requireindex both ./node_modules and ./plugins?
No, plugins to load will be listed in settings.json, so you don't need to guess what is a plugin in node_modules and all. (this is also useful to specific plugins settings in settings.json)

**Comment by demipixel** [comment]
Ah, so

- ../node_modules/plugin_name
- ./node_modules/plugin_name
- ./plugin/plugin_name

**Comment by rom1504** [comment]
* require('plugin_name')
* if that doesn't work (try catch), require('../plugins/plugin_name')

**Comment by rom1504** [comment]
Mostly done. We can create new issues for more specific stuff that might need doing.

**Comment by Creeplays** [comment]
What about writing custom event emitter, that calls every event catcher and waits for yield? (Maybe you can not understood me, sorry in this way)

**Comment by rom1504** [comment]
emit-then does that

**Comment by demipixel** [comment]
And ideally you might use a behavior (though depends on the circumstances).
