### ISSUE TITLE
Only send chunks close to the player at login

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#43]
That's what the vanilla server does : "when you login while looking at the bed rock which is 64m from you at first it's blue then only a few seconds later it loads and you can see the bedrock"

So the idea is sending the first chunks close of the player at login, not the whole column.
And then later send the chunks that are more far away.

See https://gist.github.com/rom1504/dc8d18abc1b9734926f4 for ideas into how to send chunks in a second time (the vanilla client disconnect if you send too many chunk to it too fast)

**Comment by rom1504** [comment]
Related to https://github.com/PrismarineJS/prismarine-chunk/issues/16 and https://github.com/PrismarineJS/prismarine-chunk/issues/8

**Comment by rom1504** [comment]
The way bukkit/spigot does it is sending chunks in spiral to the player, vanilla is going to do that too in 1.9.
We should probably do that too.

See https://github.com/demipixel/spiralloop for a spiral iterator maybe.

**Comment by rom1504** [comment]
Need to 
1. store the chunkX+","+chunkZ that each player already got
2. send just one chunk at login
3. keep sending chunks farther and farther away to the player until the vision distance is reached (how many chunk away is that ? 20 ? (20*16 ?))
4. when the played moved more than dX (= maybe 5) since last check, send to him the chunk he should now be able to see and that haven't be sent to him

**Comment by demipixel** [comment]
https://github.com/demipixel/spiralloop

It's up to the server how far the view distance is and I think it can be adjusted. Default is 16 chunks I believe (I think that's 8 each way or something even though that would be 17). It might be worth having a `player.on('changedChunk')` which has the old chunk and new chunk. Plugins could then use that and then sending chunks could use that as well.

**Comment by rom1504** [comment]
We could have an event similar to https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#chunkcolumnload-point yes

I'll try using your spiralloop package for this, any clue how fast it is ? I see weird things in the code, think about using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt ^^
