### ISSUE TITLE
Should flying-squid be es6 ?

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#44]
like [prismarine-world](https://github.com/rom1504/prismarine-world/blob/implementation/src/world.js#L13) and other prismarine modules (node-minecraft-protocol included) are

**Comment by Creeplays** [comment]
Noo! ECMASCRIPT4 forever! :D

**Comment by rom1504** [comment]
So yeah, it would be nice, we might even have some use for async/await (see kinda related discussion there https://github.com/PrismarineJS/prismarine-world/issues/4 )

**Comment by mhsjlw** [comment]
We can take a look at this later. For now we don't need to make this decision

**Comment by rom1504** [comment]
Well I don't know when "now" is, but it seems to me this should stay open. (Creeplays was joking)

**Comment by mhsjlw** [comment]
If you say so :P

**Comment by rom1504** [comment]
So, I think I'm going to do that, and use async/away. It would probably make sense to provide a promise API instead of a callback one.

**Comment by rom1504** [comment]
done
