### ISSUE TITLE
World generation

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#47]
Interface : 

Each world generation file should expose its stuff by doing : 
```js
module.exports = function(opt, seed) {
  function initialGeneration()
  {
   // return a World (can use opt and seed)
  }
  
  function chunkGeneration(chunkX,chunkZ)
  {
  // return a chunk
  }
  return {
    initialGeneration:initialGeneration,
    chunkGeneration:chunkGeneration
  };
}
```

chunkGeneration would be used after the first generation when needed.

**Comment by demipixel** [comment]
Well, that wouldn't do anything because when you call module.exports it wouldn't call anything else.

But ignoring that small issue, should we allow options for each chunk generated? That way there could be an option such as "opt.forceTemple" and then users can force a temple in any chunk they wish.

Also, initialGeneration should have a sizeX and sizeZ (unless you want it to always generate the same size as spawn chunks, but what if that changes...?)

**Comment by rom1504** [comment]
ah yeah sorry I forgot the returns, let me change that

**Comment by Gjum** [comment]
This client does some simple but decent world generation:
https://github.com/fogleman/Craft#terrain-generation
https://github.com/fogleman/Craft/blob/master/src/world.c

**Comment by demipixel** [comment]
Yes, but is it the same way Minecraft does it? I'm trying to do it in a way where it will seamlessly fit in when we start incorporating loading world files saved from Vanilla, and that flying-squid could pick up where it left off like a normal server.

**Comment by Gjum** [comment]
Doing it like vanilla is very complex and should better be done by using the java code rather than copying it. The link I provided was meant for a quick, but already useful test for the worldgen interface.

**Comment by rom1504** [comment]
chunk generation api is now available in (new version soon to be release) prismarine-world.
You just have to pass a generateChunk(chunkX,chunkY) function to World and it calls it when needed.

That effectively makes the World object infinite (lazily).

So all that's needed to make the world really infinite is:
1. pass a (simple) generateChunk when creating the world
2. send it (continuously) to players at the right time (see https://github.com/mhsjlw/flying-squid/issues/43 )

**Comment by rom1504** [comment]
done :)
