### ISSUE TITLE
Infinite worlds

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/flying-squid#52]

**Comment by rom1504** [comment]
Alright not quite fixed.
Bugs:
1. need to send just the top of the chunks to speed things up (see https://github.com/PrismarineJS/prismarine-chunk/issues/8 )
2. seems nmp doesn't like too much to do too many write (seems like an nmp bug)

**Comment by rom1504** [comment]
2 is fixed (kickTimeout increased + https://github.com/PrismarineJS/node-minecraft-protocol/issues/279 )

**Comment by rom1504** [comment]
The problem was compression not being done. Problem fixed.
