### ISSUE TITLE
Supporting Entities

### ISSUE THREAD

**Issue by demipixel** [mhsjlw/flying-squid#78]
I'd love to add AI, fully functioning minecarts and boats, etc to this list but I'm gonna try and keep it as simple so we can actually complete it.

- [x] Location to store all entities (non-player only I presume?)
- [x] Displaying entities and their changing to other players
- [x] /summon command and make spawn eggs work
- [x] Calculating gravity for entities (or some sort of movement so they're not static)
- [x] Item entities that will drop when mined from survival (finally, a step towards an actual playable game!)
  - [ ] Picked up by player?

**Comment by rom1504** [comment]
begun in #28

**Comment by rom1504** [comment]
mostly done, the getting picked up by player can be done in https://github.com/mhsjlw/flying-squid/issues/36
