### ISSUE TITLE
Crash at 45min

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#85]
I have no idea why, but I've noticed the server crash every 45min on rom1504.fr
There is no error.

If anyone has a clue where this might come from, please tell, this is annoying.

**Comment by rom1504** [comment]
Finally got to see the error:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Read error for ping_start : Packet data not entirely read :
        {"metadata":{"name":"ping_start","id":0,"state":"status"},"data":{},"buffer":[0,47,12,57,52,46,50,51,46,53,56,46,49,52,56,99,221,1]}
    at parsePacketData (/home/flying-squid/auto-squid/flying-squid/node_modules/minecraft-protocol/dist/transforms/serializer.js:159:37)

```
Not sure what's up with that.

**Comment by rom1504** [comment]
Could it be http://wiki.vg/Protocol#Legacy_Server_List_Ping ?

@roblabla any clue on that ?

**Comment by mhsjlw** [comment]
@rom1504 I highly doubt that. Is it possible that we are leaking memory or the process is killing itself on your machine? I ran the server all night with no crashing

**Comment by roblabla** [comment]
This means our protocol info is wrong.

**Comment by rom1504** [comment]
@mhsjlw that's because nobody added your server to its server lists.
This error up there happens in status mode, which is normally used for pinging (that happens when a server has been added to the vanilla client server list)

@roblabla that or createServer is putting the server in the wrong state for some reason ( http://wiki.vg/Protocol#Legacy_Server_List_Ping might explain it)

**Comment by roblabla** [comment]
https://github.com/mhsjlw/flying-squid/blob/master/src/lib/serverPlugins/login.js#L11 you should add an error handler in there to avoid crashing the whole server and only disconnect the user anyway.

**Comment by rom1504** [comment]
I know. The error handler is there https://github.com/mhsjlw/flying-squid/blob/master/src/lib/playerPlugins/logout.js#L32

Problem is we can't listen to the error event before login is emitted.

Since we are in the status state here, it seems nobody logined yet, which makes sense (it seems likely there's always somebody with an open client pinging my server but unlikely that somebody connect every 45min)

**Comment by rom1504** [comment]
Flying-squid only knows about the client at that point https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createServer.js#L217 , if an error happens before, crash.

**Comment by rom1504** [comment]
Ah, if we listen to the 'connection' nmp server event, we can plug the error handler before anything else happens.

**Comment by rom1504** [comment]
The buffer is [0,47,12,57,52,46,50,51,46,53,56,46,49,52,56,99,221,1]
99*256+221 == 25565

47 is the version number 

this looks like http://wiki.vg/Protocol#Handshake

0 is the packet id

Why is it trying to read the Handshake packet in status state ?

**Comment by rom1504** [comment]
Err no, not "fix", "try to fix" github.

**Comment by rom1504** [comment]
Okay now the crash stopped 20ff77bc1d8bb5d1ff367017d58ce4a20083f238

the same error remains though.

**Comment by rom1504** [comment]
It's always the same ip doing it. I think it's a badly coded bot.
That probably mean the nmp error is normal.

**Comment by rom1504** [comment]
I banned the ip from my server. Let's wait some time, if I don't get that error anymore, I'll close.

**Comment by rom1504** [comment]
Ok, problem solved.
