### ISSUE TITLE
Implement sounds

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#87]
Related to http://wiki.vg/Protocol#Sound_Effect + https://github.com/PrismarineJS/minecraft-data/issues/77

**Comment by demipixel** [comment]
Working on it.

**Comment by demipixel** [comment]
Basics of sounds + particles down.

**Comment by rom1504** [comment]
What else needs to be done here ?

**Comment by demipixel** [comment]
None that I'm aware of (other than implementing sounds in features as we add them)

**Comment by rom1504** [comment]
Okay let's close.
