### ISSUE TITLE
Invisible on respawn

### ISSUE THREAD

**Issue by demipixel** [mhsjlw/flying-squid#91]
We need to fix this. If you kill another player, they are invisible to the original player (the respawned player can still see the original player, however).

**Comment by rom1504** [comment]
For some reason playerToAdd (https://github.com/mhsjlw/flying-squid/blob/master/src/lib/playerPlugins/login.js#L31) is empty when respawning, not sure what that happens, maybe something wrong with position + getNearby()

**Comment by demipixel** [comment]
Side note: Might want to rename `nearbyPlayers` to `localPlayers` or `visiblePlayers` since there are cases (or plugins) where we might not want to spawn a nearby player.
