### ISSUE TITLE
update the doc

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#97]
Some stuff are outdated (in particular communication.js stuff)

https://github.com/mhsjlw/flying-squid/blob/master/doc/contribute.md need to be updated too now that plugins have been put together.

**Comment by rom1504** [comment]
need to update the player.entity -> player change too now.

**Comment by demipixel** [comment]
- [ ] All of the communication stuff changed (all of it moved to entity)
- [ ] We need an entity section in the doc
- [ ] Move everything from player to entity that isn't player specific (like .updateHealth or .health, any properties or functions that can be used on any entity)

**Comment by demipixel** [comment]
At least in the PR ^^^^^

**Comment by rom1504** [comment]
still need to update https://github.com/mhsjlw/flying-squid/blob/master/doc/contribute.md

**Comment by demipixel** [comment]
God damnit

**Comment by rom1504** [comment]
done
