### ISSUE TITLE
fix infinite loop

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#99]
A number of things seem to provoke 100% cpu block. For example:
* attacking someone in /gamemode 0

That's new, we should fix this.

This is probably due to player entities having entities plugins, so for example physics.js.
Got to figure out what to do about this, probably disabling some entity plugin stuff for players.
Edit: ah I guess nevermind, player don't have a velocity. so physics doesn't happen for them apparently https://github.com/mhsjlw/flying-squid/blob/master/src/lib/plugins/entities.js#L153

Edit2: well it might be fixed, I can't reproduce with /gamemode 0 now

**Comment by mhsjlw** [comment]
@rom1504 Just tested this, it makes my CPU usage spike.

**Comment by rom1504** [comment]
what does ? in what condition ? what do you mean by spike ? 100 % ?

**Comment by mhsjlw** [comment]
100% spike, when I hit someone that is in game mode 0. It is possible that I am running an older version of flying-squid, I'll double check

**Comment by rom1504** [comment]
okay I'm seeing a 100% cpu usage on my server, this is not normal, it should be fixed. Probably related with #100

**Comment by rom1504** [comment]
so, #103 is solved.

Can anybody find some other case of 100% cpu ?

**Comment by rom1504** [comment]
I think this is fixed, we can reopen if needed.
